package net.shasankp000.GameAI.autonomous;

/**
 * A single entry in the autonomous goal queue.
 *
 * @param goalText   Natural-language goal string fed into GoalMapper.
 * @param priority   Higher value = processed first. Normal LLM goals = 0,
 *                   world-event injections = 10.
 * @param source     Where this goal came from (for logging / debug).
 */
public record GoalQueueEntry(String goalText, int priority, Source source)
        implements Comparable<GoalQueueEntry> {

    public enum Source {
        /** Generated by the LLM on spawn or scheduled re-plan. */
        LLM_PLAN,
        /** Injected by WorldEventListener in response to a server event. */
        WORLD_EVENT,
        /** Directly requested by a human player via chat. */
        PLAYER
    }

    /** Higher priority sorts to the front of the queue. */
    @Override
    public int compareTo(GoalQueueEntry other) {
        return Integer.compare(other.priority(), this.priority());
    }
}
