# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties (keep your existing values)
mod_version=1.0.6.2-release+26.1
maven_group=net.shasankp000
archives_base_name=ai-player

# Dependencies
fabric_version=0.155.2+26.1.2
